### ISSUE TITLE
Estimation package?

### ISSUE THREAD

**Issue by kofron** [JuliaDSP/Roadmap#2]
Would people like to see a package belonging to JuliaDSP that does estimation?  For example, I use the quinn-fernandes estimator for single sinusoid frequency, and will probably be implementing a few more soon.  
There are also spectral estimators like ARMA, AR, etc - thoughts?

**Comment by rob-luke** [comment]
I would find this useful, and imagine other would too.

**Comment by jfsantos** [comment]
That would be certainly a good addition to JuliaDSP and I would be glad to contribute.

**Comment by kofron** [comment]
ok, awesome.  I have a very basic Estimation.jl package right now that only includes the quinn-fernandes frequency estimator.  i can transfer ownership to the JuliaDSP org, if that's the best way to proceed, and then we can all hack away at it?

**Comment by jfsantos** [comment]
I think that could be a good approach. As soon as you transfer ownership I'll add you as an owner.

**Comment by kofron** [comment]
Will do - but I need to be owner before I can transfer the repo.  I'm ready whenever.

**Comment by jfsantos** [comment]
Oops, sorry for that! I sent you an invite for the organization.
