### ISSUE TITLE
please invite multirate.jl

### ISSUE THREAD

**Issue by bjarthur** [JuliaDSP/Roadmap#5]

**Comment by bjarthur** [comment]
https://github.com/JayKickliter/Multirate.jl

**Comment by jfsantos** [comment]
@JayKickliter, would you like to join the JuliaDSP organization? There's a lot of good stuff in Multirate.jl and Radio.jl and we would be glad to contribute to these packages!

**Comment by JayKickliter** [comment]
Yes, definitely.

I'm really sorry for taking so long to submit a pull request to merge Multirate into DSP. I just started a new a job at a startup, and haven't had the time to do anything on the side. I'd appreciate any help I can get.

**Comment by jfsantos** [comment]
I completely understand! DSP.jl is not moving really fast nowadays so we will not break things in Multirate anytime soon. We should define first whether it would be better to keep some things in a separate package or if everything should be in DSP. We definitely want FIR design in DSP, and it would be nice to have streaming and resampling filters.

Maybe one thing we could do is start a separate branch and add the separate modules in Multirate.jl. Then we could do things like adapting APIs to make sure all functions follow the same style.

@simonster, @gummif, any other suggestions?

**Comment by gummif** [comment]
Merging everything to a branch then adapting the code as people have time sounds good to me.

**Comment by simonster** [comment]
+1 for putting this in a branch. I think everything in Multirate.jl should eventually go into DSP.jl. Unfortunately I'll be quite busy for the next couple of months, so I may not be able to help much in the near future.

**Comment by JayKickliter** [comment]
Sorry, I've been working 7 days a week for the last couple months on several [hardware designs](http://techcrunch.com/2014/12/09/helium/). I think I might have some free time this weekend. If not, I think I may just transfer ownership of the Multirate repository to JuliaDSP if you want. Hopefully it doesn't come to that, but I've been promising this code for almost year now, and would like to help to integrate it into the DSP.jl package. Especially while the concepts still make sense to me.

**Comment by jfsantos** [comment]
No problem, I think we are all busy right now!

**Comment by JayKickliter** [comment]
I have a little more free time now, is the invitation still open?

Once we get Multirate.jl merged into DSP.jl, I plan on working on Radio.jl again and transferring to it JuliaDSP.

**Comment by simonster** [comment]
@JayKickliter Just sent you an invitation to be a JuliaDSP admin.
