### ISSUE TITLE
Commenting & documentation

### ISSUE THREAD

**Issue by rob-luke** [JuliaDSP/Roadmap#6]
Im soon to upload an APES spectral estimator to the estimation package.
But I had some questions about commenting and documentation first.

Is there was a standard julia practice for commenting within code?
I see quite a variety of styles within the DSP organisation.

Also I have been using Docile.jl to keep my documentation and comments organised.
DSP uses readthedocs, wavelets seems hand written, and estimation uses nothing.
Should I use a particular system to minimise upkeep of these packages?

**Comment by gummif** [comment]
I'm personally waiting for the standard documentation system, see
https://github.com/JuliaLang/julia/pull/8791
https://github.com/JuliaLang/julia/issues/8966

**Comment by jfsantos** [comment]
That's exactly what I was going to say. Many packages (like DSP) currently use Sphinx and host the documentation at readthedocs, but I think we should move to the standard documentation system later (at least for inline documentation at first, and then I am sure somebody will come up with an inline-to-Readthedocs-friendly converter in a snap).

**Comment by rob-luke** [comment]
Thanks for the feedback.
I used Docile for the estimation package, and will adjust the code as required when the standard documentation system goes online.

**Comment by jfsantos** [comment]
Great. Docile looks a lot like the new doc system, so the transition will probably be easy.
