### ISSUE TITLE
Signal extensions

### ISSUE THREAD

**Issue by gummif** [JuliaDSP/Roadmap#7]
I'm thinking a package maybe called SignalExtensions.jl might be useful (or possible a module in DSP.jl).

You could take your signal which might be of weird length, and extend (extrapolate) it in some way to a nice length like a power of 2. Then you can do your `fft`s or wavelet transforms without worries and with better performance. E.g.

``` julia
x0 = randn(121)  # some data
x = Array(Float64, nextpow2(121))
offset = 3
extend!(x, x0, MirrorExt, offset)
# or PeriodicExt, ZeroExt, LinearExt, ...
# and possibly apply windowing to the extended range to smooth out the boundaries
```

Any thoughts?

**Comment by jfsantos** [comment]
That would be a nice addition to DSP, I think. I also have some issues with running STFTs and ISTFTs on signals of weird dimensions, and that's the reason I wanted to add a padding option to our `ArraySplit` implementation. Maybe we could do it both for signals and for `ArraySplit`s?

**Comment by jfsantos** [comment]
Since this is going to be added to DSP.jl, I am going to close this issue.
